### ISSUE TITLE
Remove init files

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-payment-provider-template#4]
@mattbrailsford I noticed you removed the `Init.cmd` and `Init.ps1` in Square payment provider here:
https://github.com/vendrcontrib/vendr-payment-provider-square/commit/6a3d8a2b4630e792dfad3a570d7ff6ec05cdb5f3

So if we don't need these, it would be great to remove these from template project as well 👍

**Comment by mattbrailsford** [comment]
The Init scripts are only needed to initialise the project once you fork the template so they are required in the template project, but once you’ve run them and setup your project they are no longer required. Hence why I removed them in the Square payment provider repo.

**Comment by bjarnef** [comment]
Ahh okay. Actually have used them (I guess I renamed the naming the hard way) 😅
It is kinda similar to the UaaS.cmd for Umbraco Cloud project where it seems to fill the namespace, project name etc.
